# Generated by Django 4.0.6 on 2022-07-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SERVICE', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
