# Generated by Django 4.0.6 on 2022-08-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SERVICE', '0005_college'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='SOS_COLLEGE',
        ),
    ]
