# Generated by Django 4.0.6 on 2022-08-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERVICE', '0009_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectDescription', models.CharField(max_length=50)),
                ('course_ID', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SOS_SUBJECT',
            },
        ),
    ]
